#!/bin/bash
hostnamectl set-hostname br-rtr;

cat > /etc/sysconfig/network <<EOF
NETWORKING=yes
CONFMETHOD=etcnet
HOSTNAME=br-rtr.au-team.irpo
DOMAINNAME=localdomain
RESOLV_MODS=yes
EOF

#Chrony

sed -i 's/pool pool.ntp.org iburst/pool 172.16.1.1 iburst/g'

exec bash
