#!/bin/bash
hostnamectl set-hostname br-rtr;

cat > /etc/sysconfig/network <<EOF
NETWORKING=yes
CONFMETHOD=etcnet
HOSTNAME=br-rtr.au-team.irpo
DOMAINNAME=localdomain
RESOLV_MODS=yes
EOF



exec bash
