#!/bin/bash
hostnamectl set-hostname br-rtr;exec bash

cat <<EOF > /etc/sysconfig/network
NETWORKING=yes
CONFMETHOD=etcnet
HOSTNAME=br-rtr.au-team.irpo
DOMAINNAME=localdomain
RESOLV_MODS=yes
EOF
