#!/bin/bash
hostnamectl set-hostname hq-cli;
cat  > /etc/sysconfig/network <<EOF
NETWORKING=yes
CONFMETHOD=etcnet
HOSTNAME=hq-cli.au-team.irpo
DOMAINNAME=localdomain
RESOLV_MODS=yes
EOF








#Время
apt-get update
apt-get install tzdata
find /usr/share/zoneinfo -name Krasnoyarsk
timedatectl set-timezone Asia/Krasnoyarsk
timedatectl




#Chrony
apt-get update && apt-get install -y chrony tzdata
sed -i 's/pool pool.ntp.org iburst/pool 172.16.1.1 iburst/g' /etc/chrony.conf
systemctl restart chronyd   



# Монтирование RAID 
mkdir /mnt/nfs

# Файл options
cat >> /etc/fstab <<EOF
192.168.100.2:/raid/nfs /mnt/nfs nfs rw 0 0
EOF
mount -a
ls /mnt/nfs

# Создание пользователя sshuser с UID 2027 (МЕНЯЙТЕ ИМЯ И Т.Д В ЗАВИСИМОСТИ ОТ ЗАДАНИЯ)
useradd -u 2027 -m sshuser

# Установка пароля P@ssw0rd без подтверждения
echo "sshuser:P@ssw0rd" | chpasswd

# Добавление в группу wheel
gpasswd -a sshuser wheel

# Настройка sudo без пароля
echo "sshuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Настройка SSH
sed -i 's/#Port 22/Port 2027/' /etc/openssh/sshd_config
sed -i 's/#PermitRootLogin without-password/PermitRootLogin no/' /etc/openssh/sshd_config
echo "AllowUsers sshuser" >> /etc/openssh/sshd_config
echo "MaxAuthTries 2" >> /etc/openssh/sshd_config
echo "Banner /etc/openssh/banner" >> /etc/openssh/sshd_config

# Создание баннера
echo "Authorized access only" > /etc/openssh/banner

# Перезапуск SSH
systemctl restart sshd

echo "Настройка завершена:"
echo "- Пользователь: sshuser (пароль: P@ssw0rd)"
echo "- SSH порт: 2027"
echo "- Root-логин запрещен"
echo "- Баннер создан"


№Настройка хоста
cat > /etc/hosts << EOF
127.0.0.1 localhost.localdomain localhost
::1 localhost6.localdomain localhost6
172.16.1.1 web.au-team.irpo
172.16.2.1 docker.au-team.irpo
192.168.100.2 hq-srv.au-team.irpo
EOF



# Файл /etc/resolv.conf
sed -i 's nameserver 77.88.8.8/    nameserver 192.168.100.2
    search au-team.irpo/g' /etc/resolv.conf
exec bash
